### PR TITLE
fix server connexions from ignition

### PR DESCRIPTION
**Pull request by lovasoa**
Fixes https://github.com/locka99/opcua/issues/182

Reverts a change introduced in 5c20ed8f1d3b708b5c0441528eea792a9607fa07

### CODE REVIEW

**Comment by svanharmelen** [comment]
Reverting the change like this (so in full) will reintroduce the problems that were solved by this change. So I suggest to look for a solution that solves this particular issue, instead of rolling back the whole change...

**Comment by lovasoa** [comment]
@svanharmelen : Did you look at the pr ? This is not a simple git revert of the previous change. The previous change did not include any comment, but I suppose it introduced an all-zeroes nonce to force connections to clients that require a nonce during secure channel creation. This pr keeps the nonce, but makes it an actual random nonce, as required by the spec.

**Comment by svanharmelen** [comment]
Looks like I might have mixed things up... I was looking at [this](https://github.com/locka99/opcua/pull/183/files#diff-c1177d127d0a14e056ad2ce44df9c5b63244b1d9889862a1a965c5f030aa89a1L275-L284) part which make me think of this change: https://github.com/locka99/opcua/pull/114/files

But it seems your change is not touching that code actually 👍🏻

**Comment by lovasoa** [comment]
@locka99 : is there something you want me to do before this can be merged ? We depend on this for our server.

**Comment by locka99** [comment]
I'll take it since it uses a zero length array instead of null but we'll to monitor if it makes any servers unhappy. & thanks for your persistence in this.

**Comment by locka99** [comment]
I just noticed SecurityPolicy::None is given a 32 byte array. Can you check please if 0 works?

**Comment by lovasoa** [comment]
I am no expert, but see https://github.com/eclipse/milo/pull/949 : 

>> is it a standard-compliant behavior to send a null nonce ?
>
> It is only compliant when the null nonce is in the OpenSecureChannelResponse and the channels are not using security.
>
> There are other nonce exchanges, in the CreateSessionResponse and ActivateSessionResponse, and in these it is important in regards to the CVE that the nonce be non-empty and non-zero if they are going to be used in the subsequent encryption of credentials for transit on an otherwise unsecure channel.

**Comment by locka99** [comment]
There is a underlying difference between a null bytestring and a zero length bytestring. It may be that using 0 satisfies everyone instead of null. I'll have to see if the specs say because this stuff has been a constant bane - some server complains when there is a nonce and others complain when there is a null.

**Comment by locka99** [comment]
I'll release a 0.9.1 with your changes cherry-picked into it

**Pull request merged**
