### PR TITLE
Tokio 0.2

### PR DESCRIPTION
**Pull request by nkbai**
sync with master

### CODE REVIEW

**Comment by nkbai** [comment]
@svanharmelen  I have synced with master. and all tests are passed.

**Comment by svanharmelen** [comment]
Thanks @nkbai, but I think your were too quick as PR #75 isn’t merged into master yet...

My PR to this branch (#76) is based on the formatting changes added in #75, so you should probably try to rebase against #75 or  try to merge #76 (which actually is a rebase from this branch against #75) into the tokio-0.2 branch.

Sorry for the confusion and thanks for the help!

**Comment by locka99** [comment]
The master now has been formatted. I suggest this for the branch:

1. cherry pick 154995ce. This brings in the new rustfmt.toml and also exempts the autogenerated files
2. cargo fmt
3. merge from master

I am not sure if this will cause a lot of conflicts or not. If it does we can revert the b56e4074 commit where "cargo fmt" was run on the master until tokio-0.2 lands

**Comment by svanharmelen** [comment]
I guess there will be quite some conflicts... Another approach could be:

1. Checkout 3eefdb8 (from the tokio-0.2 branch) to a temp branch
1. Cherry pick 154995c, this brings in the new rustfmt.toml and also exempts the autogenerated files
2. Run `cargo fmt --all`
3. Squash 3eefdb8, 154995c and the commit that contains the `cargo fmt --all` changes into 1 commit
4. Rebase from master (there will be merge conflicts but not too many, and remember to ignore all format changes to generated files)
5. Cherry pick all commits of the tokio-0.2 branch after commit 3eefdb8

Just tried this myself and was very doable. Super open to making a PR for it if you want, yet the PR cannot be merged directly. Instead it's a change (rebase of the branch) that requires a force push...

**Comment by locka99** [comment]
I don't think that should be necessary. Since @nkbai has merged up to the head of master prior to the reformat, if there are conflicts from merging master after reformatting then it should be possible to resolve them conflicts in favour of the local changes.

**Comment by svanharmelen** [comment]
I always try to avoid merging master into a feature branch, but thats probably just a personal thing 😏

**Comment by locka99** [comment]
I'll take this one in and the formatting can happen whenever is easiest.

**Comment by nkbai** [comment]
@locka99  Do I need sync with master again?  `rustfmt.toml` is empty now。

**Pull request merged**
