### PR TITLE
Fix a few clippy warnings

### PR DESCRIPTION
**Pull request by lovasoa**
There is no functional change, this only fixes a few clippy warnings, making the code a little bit more readable.

### CODE REVIEW

**Comment by lovasoa** [comment]
The failed tests are not linked to the contents of the pr

**Comment by svanharmelen** [comment]
Please note (to prevent double efforts) that PR #146 already fixes almost all clippy warnings.

**Comment by lovasoa** [comment]
@svanharmelen : Yes, I saw your pr, it looks great ! I really hope it will be merged someday, but it looks like it's going to take a lot of time. And I can't blame @locka99, I know how large PRs are hard to review, especially for a side project to which you cannot allocate a lot of time/ !

**Comment by svanharmelen** [comment]
Fair point...

**Pull request closed without merging**
